# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    MAKEFILE                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: gbradel <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/11/23 17:31:38 by gbradel           #+#    #+#              #
#    Updated: 2016/12/01 14:53:45 by gbradel          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a
FLAGS = -Wall -Werror -Wextra
SRC = ft_lstmap.c ft_lstiter.c ft_lstadd.c ft_lstdel.c ft_lstdelone.c \
	  ft_lstnew.c ft_putnbr_fd.c ft_putendl_fd.c ft_putstr_fd.c ft_putchar_fd.c\
	  ft_strsplit.c ft_itoa.c ft_putendl.c ft_strtrim.c ft_strjoin.c ft_strsub.c\
	  ft_strnequ.c ft_strequ.c ft_strmapi.c ft_strmap.c ft_striteri.c\
	  ft_striter.c ft_strclr.c ft_strdel.c ft_strnew.c ft_memdel.c ft_memalloc.c\
	  ft_atoi.c ft_strncmp.c ft_memset.c ft_putchar.c ft_putnbr.c ft_putstr.c\
	  ft_strcpy.c ft_strdup.c ft_strlen.c ft_strncpy.c ft_bzero.c ft_memcpy.c\
	  ft_memccpy.c ft_memmove.c ft_memchr.c ft_memcmp.c ft_strcat.c ft_strncat.c\
	  ft_strlcat.c ft_strchr.c ft_strrchr.c ft_strstr.c ft_strnstr.c ft_strcmp.c\
	  ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c ft_isprint.c ft_toupper.c\
	  ft_tolower.c

OBJ = $(SRC:.c=.o)

$(NAME):
		gcc $(FLAGS) -c $(SRC)
		ar -rc $(NAME) $(OBJ)

clean:
		rm -rf $(OBJ)

fclean: clean
		rm -rf $(NAME)

re: fclean all

all: $(NAME)
